development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username:  a
  password:
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username:  a
  password:
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  username: a
  password:
  port: 5432